### ISSUE TITLE
F17 (and F18) not supported

### ISSUE THREAD

**Issue by 4ndrej** [xsuchy/fedora-upgrade#15]
Hello,
it seems that since d5ef3bfd2bfc24a3b113c63be1aca557a25e65f1 the upgrade from F17 (and F18) is not supported anymore but it's announced in Readme file.

**Comment by xsuchy** [comment]
Fixed.

**Comment by 4ndrej** [comment]
well, I upgraded from F17 to F18 to F19 using this script recently so I don't know why you removed the support for prehistoric fedoras.

**Comment by xsuchy** [comment]
Because this script target only supported version. Upgrade from historic version are still kept in historic version included directly in Fedora distributions.  You should not run script from this git directly, you should always 'yum install fedora-upgrade'

**Comment by 4ndrej** [comment]
Oh, I see.
Thanks for explanation (and for wonderfull fedora-upgrade tool too).
