### ISSUE TITLE
Comparing src packages behaves strange

### ISSUE THREAD

**Issue by m-blaha** [xsuchy/fedora-upgrade#26]
The remove-retired-packages compares source packages and than removes binary packages. This results in kind of unexpected behaviour. For example `nspr` package in F33 is build from `nspr-4.32.0-1.fc33.src.rpm` source, but on F34 from `nss-3.69.0-1.fc34.src.rpm`. The `nspr` source package does not exist any more. This results in attempt to remove `nspr` binary package which is not retired, only is built from another source.

**Comment by m-blaha** [comment]
The other example is retired `hub` F33 source package resulting in attempt to remove F34 `hub` binary package which is built from unretired `golang-github-hub` source.

**Comment by xsuchy** [comment]
Should be resolved by 28921c0
