### ISSUE TITLE
remove-retired-packages: Skipping a single packages, skips all  remaining packages

### ISSUE THREAD

**Issue by Woi** [xsuchy/fedora-upgrade#35]
Description:
Skipping a single packages quits `remove-retired-packages`, thus preventing removal of subsequent packages.

Desired behavior:
After skipping a package by pressing `n`, `remove-retired-packages` continues with remaining packages.

Note:
It seems this is a regression introduced by https://github.com/xsuchy/fedora-upgrade/commit/433b7d3cbbaaa34a5cb95c5310aac417595d7f3e
However reverting https://github.com/xsuchy/fedora-upgrade/commit/433b7d3cbbaaa34a5cb95c5310aac417595d7f3e prevents quitting  `remove-retired-packages` by pressing `CTRL + C`

**Comment by Woi** [comment]
Downstream bug report:
https://bugzilla.redhat.com/show_bug.cgi?id=2086345

**Comment by xsuchy** [comment]
I agree. This need to be enhanced.
