### ISSUE TITLE
What is XXXXXXXXXXXX?

### ISSUE THREAD

**Issue by dreua** [xsuchy/fedora-upgrade#40]
https://github.com/xsuchy/fedora-upgrade/blob/a20f01ba30bf0499956a7c49db567064aa3a4166/remove-retired-packages#L35

Can someone help me out here? What purpose does the `XXXXXXXXXXXX` have? Thanks :)

**Comment by xsuchy** [comment]
Git blame points me to
https://github.com/xsuchy/fedora-upgrade/commit/0bdbe06f70eec30b60845ca860e7ebe31b8bc34e

**Comment by dreua** [comment]
I know git Blake but still fail to understand the reason for XXXX... Is it just a variable / placeholder? Why not give it a more meaningful name?

**Comment by xsuchy** [comment]
When you have new repository, from which DNF never imported GPG key, then the user experience is as follows:

echo Gathering package list for Fedora $UPGRADE_FROM
... wait.
... dnf is downloading data, packages....
... wait (you likely go away from keyboard
... dnf asks you to import gpg key
.... wait
... you return to keyboard in hope that the transaction finished and it did not even start yet

With this line, I ask if package XXXXXX exists. It does not exist. I know but DNF is forced to download repodata and asks you for missing GPG key. So the experience is:
echo Gathering package list for Fedora $UPGRADE_FROM
... dnf asks you to import gpg key
... wait
... wait (you likely go away from keyboard)
... wait
... you return back and everything is finished)

**Comment by dreua** [comment]
Alright so it is just a placeholder for a not existing package name, I might have called it something like xxx_nonexistent_package_xxx to be more explicit about its purpose. Thanks for the clarification!
