### ISSUE TITLE
Add support for DNF5

### ISSUE THREAD

**Issue by praiskup** [xsuchy/fedora-upgrade#47]
I'd like to upgrade my system using DNF5 as an early adopter.  It would be ideal if
I was asked like:

```
Choose the package manager:
  * dnf4 - ....
  * dnf5 - ...
What is your choice? (dnf4/dnf5)
```

**Comment by praiskup** [comment]
Note that `--best` [is not the default ATM](https://github.com/rpm-software-management/dnf5/issues/934) so I'm going with `$ sudo dnf distro-sync --releasever 39 --best`

**Comment by praiskup** [comment]
```
Transaction Summary:                                                                                                                                                                                                                         
 Installing:       69 packages                                                                                                                                                                                                               
 Reinstalling:      2 packages                                                                                                                                                                                                               
 Upgrading:      4460 packages                                                                                                                                                                                                               
 Replacing:      4543 packages                                                                                                                                                                                                               
 Removing:         14 packages                                                                                                                                                                                                               
 Downgrading:      61 packages                                                                                                                                                                                                               
                                                                                                                                                                                                                                             
Total size of inbound packages is 6 GiB. Need to download 6 GiB.                                                                                                                                                                             
After this operation 484 MiB will be used (install 19 GiB, remove 18 GiB).                                                                                                                                                                   
Is this ok [y/N]: y
```

**Comment by jyxjjj** [comment]
After upgrading to Fedora 41, DNF5 is used by default.
The warning "No matches were found for the following plugin name patterns while disabling libdnf plugins: local" will appear.

Try removing all support for DNF3 and DNF4, the only package affected will be this one : `remove-retired-packages`

This point is not mentioned in the Fedora documentation.

![image](https://github.com/user-attachments/assets/2ad6b6d0-d2fd-471e-b07e-3dbf54a0d972)
![image](https://github.com/user-attachments/assets/eec5de44-354d-43ea-8d07-940c24df3473)
![image](https://github.com/user-attachments/assets/6115e13f-caa4-4d93-b8be-0a9b4ac65368)

**Comment by xsuchy** [comment]
> The warning "No matches were found for the following plugin name patterns while disabling libdnf plugins: local" will appear.

This is just information text.

> Try removing all support for DNF3 and DNF4, the only package affected will be this one : remove-retired-packages
> This point is not mentioned in the Fedora documentation.

Not sure what you mean.

**Comment by xsuchy** [comment]
As per original report this uses default DNF. I have no intention to specially handling DNF{4,5}. So on upgrading from F41 to 42 it will automatically start using DNF5.

**Comment by jyxjjj** [comment]
> > The warning "No matches were found for the following plugin name patterns while disabling libdnf plugins: local" will appear.
> 
> 
> 
> This is just information text.
> 
> 
> 
> > Try removing all support for DNF3 and DNF4, the only package affected will be this one : remove-retired-packages
> 
> > This point is not mentioned in the Fedora documentation.
> 
> 
> 
> Not sure what you mean.

I mean this package still depends on dnf4, i think it should be a weak dependence when on 41. Okay or it may will be fixed when 40 is EOL. Then the document should mention that.
