### ISSUE TITLE
remove-retired-packages crashed, can't find logs.

### ISSUE THREAD

**Issue by not-a-sysadmin** [xsuchy/fedora-upgrade#51]
This past Thursday (October 10), I upgraded from Fedora-39 to Fedora-40.  After that, as a part of the "optional post-upgrade tasks" recommended in the "Upgrading Fedora Linux Using DNF System Plugin" document, I ran "remove-retired-packages".  It went fine for a few packages, but then either hung my workstation or crashed in the midst of one package removal.  After rebooting, I again ran the tool with no further problems.  However, it seemed to remove an unusually large amount of packages, and a large amount of parts in some of those packages.  Afterwards, I tried to find logs from the tool's runs, but could not.  The tool's man page gives no hint of logs or where to find them.

1. Please add good logging to your tool.
2. Please add to the tool's man page information on where to find the logs.

I'd like to be able to provide information to help with the hang/crash and the possible over-kill of the removals, but without logs, I can't.

My workstation was severely crippled after the tool run, and I'm wondering if your tool's hang/crash had something to do with that.  It took a long and difficult thread in the Fedora users list to repair my workstation.  The absence of logs from your tool really hindered me from giving list members the information needed to resolve the issue.

**Comment by xsuchy** [comment]
`remove-retired-packages` is built on top of dnf. So you can use `dnf history list` and `dnf history info $NUMBER`. 

I agree that it would be nice to add to the documentation.

**Comment by not-a-sysadmin** [comment]
Thank-you for your reply.

`remove-retired-packages` does produce some output before it starts the dnf calls.  It would be good to have that logged so I can afterwards quickly and easily see what it proposed to delete. It might also be helpful to see reasons and sizes in the tool logs.

I tried what you suggested.  It helped.  I will post a separate comment with results of your suggested commands in hope that it can help determine if something is wrong with the tool, and if so, what.

By the way, there should be no '$' in front of the ID number.

**Comment by not-a-sysadmin** [comment]
Having used the commands you gave me in your earlier post, I have more information that I hope can help you determine if the tool has a bug, and diagnose and fix it if there is a bug.

"dnf history list" output was redirected to a text file, which I trimmed down to the relevant lines.  That's is the first attachment (dnfhist.txt).
[dnfhist.txt](https://github.com/user-attachments/files/17357329/dnfhist.txt)
The hang/crash occurred during 1665.  I had to reboot.

Using "dnf history info 1665" and redirecting to a text file, I got a little information on the remove that crashed/hung.  That's in the second attachment (info1665.txt).
[info1665.txt](https://github.com/user-attachments/files/17357345/info1665.txt)

I have no sys.admin. training.  I'm stuck doing my own sys.admin. on my home workstation, where the problem occurred.  I hope that what I provided helps.  If you need/want more, please ask.  Because I'm not a real  sys.admin, give clear, specific instructions.  I'll try.
