### ISSUE TITLE
Fedora 41: No env/group "Minimal install"

### ISSUE THREAD

**Issue by dschwoerer** [xsuchy/fedora-upgrade#52]
I could not find an environment or group "Minimal install".
```
root@panhu:~# dnf5 environment list|grep -i Min 
Updating and loading repositories:
Repositories loaded.
root@fedora:~# dnf5 group list|grep -i Min
Updating and loading repositories:
Repositories loaded.
admin-tools                 Administration Tools                              yes
```
Also, the sub-command `groupupdate` does not exist for dnf5 - it needs to be either `dnf5 update @env-id` or `dnf5 group update <group-id>` (if I remember correctly)

**Comment by xsuchy** [comment]
The group "minimal install" does not exists now. Or anything similar.
I simply remove this step.
Fixed in 88d82f5
